# Generated by Django 6.1 on 2026-08-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=50, unique=True, verbose_name='Refund ID')),
                ('gst_tpn', models.CharField(max_length=15, verbose_name='GST TPN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period')),
                ('claim_date', models.DateField(verbose_name='Claim Date')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Claimed Amount')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Adjustment')),
                ('refund_disallowed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refund Disallowed')),
                ('refund_approved', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refund Approved')),
                ('refund_adjustment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Refund Adjustment %')),
                ('processing_days', models.IntegerField(default=0, verbose_name='Processing Days')),
                ('processed_date', models.DateField(blank=True, null=True, verbose_name='Processed Date')),
                ('processed_by', models.CharField(blank=True, max_length=100, verbose_name='Processed By')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('paid', 'Paid'), ('closed', 'Closed')], default='submitted', max_length=20, verbose_name='Status')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Refund Reason')),
                ('reason_code', models.CharField(blank=True, max_length=50, verbose_name='Reason Code')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund Register',
                'verbose_name_plural': 'Refund Registers',
                'ordering': ['-claim_date'],
                'indexes': [models.Index(fields=['refund_id'], name='refunds_ref_refund__a6f441_idx'), models.Index(fields=['gst_tpn'], name='refunds_ref_gst_tpn_0ae6f9_idx'), models.Index(fields=['tax_period'], name='refunds_ref_tax_per_ce4d3c_idx'), models.Index(fields=['status'], name='refunds_ref_status_57d4ea_idx'), models.Index(fields=['claim_date'], name='refunds_ref_claim_d_5716b5_idx')],
            },
        ),
    ]
