# Generated by Django 6.1 on 2026-08-14 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_refund', '0002_remove_refund_audit_refun_refund__cb6b48_idx_and_more'),
        ('compliance', '0003_complianceriskreferral_assessor'),
        ('refunds', '0001_initial'),
        ('returns', '0018_alter_gstreturn_tax_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundregister',
            name='audit_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_refunds', to='audit_refund.auditcase', verbose_name='Audit Case'),
        ),
        migrations.AddField(
            model_name='refundregister',
            name='gst_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.gstreturn', verbose_name='GST Return'),
        ),
        migrations.AddField(
            model_name='refundregister',
            name='risk_referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.complianceriskreferral', verbose_name='Risk Referral'),
        ),
    ]
