# Generated by Django 6.1 on 2026-08-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refundregister_audit_case_refundregister_gst_return_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refundregister',
            name='refunds_ref_refund__a6f441_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundregister',
            name='refunds_ref_gst_tpn_0ae6f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundregister',
            name='refunds_ref_tax_per_ce4d3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundregister',
            name='refunds_ref_status_57d4ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='refundregister',
            name='refunds_ref_claim_d_5716b5_idx',
        ),
        migrations.DeleteModel(
            name='RefundRegister',
        ),
    ]
