# Generated by Django 6.1 on 2026-08-07 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returns', '0004_alter_gstreturn_compliance_status_and_more'),
        ('taxpayers', '0011_alter_taxpayermaster_dzongkhag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_on_time', models.BooleanField(default=True, verbose_name='Filing On Time')),
                ('payment_on_time', models.BooleanField(default=True, verbose_name='Payment On Time')),
                ('notification_compliance', models.BooleanField(default=True, verbose_name='Notification Compliance')),
                ('trust_level', models.CharField(choices=[('highly_trustworthy', 'Highly Trustworthy'), ('trustworthy', 'Trustworthy'), ('moderate', 'Moderate'), ('low_trust', 'Low Trust'), ('untrustworthy', 'Untrustworthy')], default='moderate', max_length=30, verbose_name='Trust Level')),
                ('trust_score', models.IntegerField(default=50, verbose_name='Trust Score (0-100)')),
                ('compliance_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='fair', max_length=20, verbose_name='Compliance Status')),
                ('compliance_score', models.IntegerField(default=50, verbose_name='Compliance Score (0-100)')),
                ('assessment_period', models.CharField(max_length=20, verbose_name='Assessment Period (e.g., Jan-2026)')),
                ('assessment_date', models.DateField(auto_now_add=True, verbose_name='Assessment Date')),
                ('compliance_notes', models.TextField(blank=True, verbose_name='Compliance Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Assessed By')),
                ('gst_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='returns.gstreturn')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='taxpayers.taxpayermaster')),
            ],
            options={
                'verbose_name': 'Compliance Monitoring',
                'verbose_name_plural': 'Compliance Monitoring',
                'ordering': ['-assessment_date', 'taxpayer'],
                'indexes': [models.Index(fields=['taxpayer', 'assessment_period'], name='compliance__taxpaye_e581b3_idx'), models.Index(fields=['compliance_status'], name='compliance__complia_e18158_idx'), models.Index(fields=['trust_level'], name='compliance__trust_l_79e90b_idx'), models.Index(fields=['assessment_date'], name='compliance__assessm_91413c_idx')],
                'unique_together': {('taxpayer', 'assessment_period')},
            },
        ),
    ]
