# Generated by Django 6.1 on 2026-08-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Compliance ID')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period')),
                ('assessment_date', models.DateField(auto_now_add=True, verbose_name='Assessment Date')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('filing_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Filing Status')),
                ('filing_delay', models.IntegerField(blank=True, default=0, null=True, verbose_name='Filing Delay (Days)')),
                ('payment_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Payment Status')),
                ('compliance_status', models.CharField(blank=True, choices=[('Compliant', 'Compliant'), ('Late Filer', 'Late Filer'), ('Non-Filer', 'Non-Filer'), ('Payment Default', 'Payment Default'), ('Other Non-Compliance', 'Other Non-Compliance')], max_length=30, null=True, verbose_name='Compliance Status')),
                ('compliance_flag', models.CharField(blank=True, choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Red', 'Red')], max_length=10, null=True, verbose_name='Compliance Flag')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance & Enforcement',
                'verbose_name_plural': 'Compliance & Enforcement',
                'ordering': ['-tax_period', 'taxpayer_name'],
                'indexes': [models.Index(fields=['gstin', 'tax_period'], name='compliance__gstin_a68627_idx'), models.Index(fields=['tax_period'], name='compliance__tax_per_362ff8_idx'), models.Index(fields=['compliance_status'], name='compliance__complia_e18158_idx'), models.Index(fields=['compliance_flag'], name='compliance__complia_8a08b6_idx')],
                'unique_together': {('gstin', 'tax_period')},
            },
        ),
        migrations.CreateModel(
            name='EnforcementRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Case ID')),
                ('tax_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax Period')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('case_type', models.CharField(blank=True, choices=[('Non-Filing', 'Non-Filing'), ('Non-Payment', 'Non-Payment'), ('Recovery', 'Recovery'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Case Type')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount Due')),
                ('notice_date', models.DateField(blank=True, null=True, verbose_name='Notice Date')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='Action Taken')),
                ('amount_recovered', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount Recovered')),
                ('status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Follow-up', 'Follow-up'), ('Recovered', 'Recovered'), ('Closed', 'Closed')], max_length=20, null=True, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enforcement & Recovery',
                'verbose_name_plural': 'Enforcement & Recovery',
                'ordering': ['-created_at', 'case_id'],
                'indexes': [models.Index(fields=['gstin'], name='compliance__gstin_3cca63_idx'), models.Index(fields=['case_type'], name='compliance__case_ty_16536c_idx'), models.Index(fields=['status'], name='compliance__status_734165_idx'), models.Index(fields=['tax_period'], name='compliance__tax_per_8b7142_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRiskReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Risk ID')),
                ('assessment_from_period', models.CharField(max_length=20, verbose_name='Assessment From Period')),
                ('assessment_to_period', models.CharField(max_length=20, verbose_name='Assessment To Period')),
                ('assessment_date', models.DateField(auto_now_add=True, verbose_name='Assessment Date')),
                ('assessment_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Assessment Status')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('risk_type', models.CharField(blank=True, choices=[('Filing & Payment Risk', 'Filing & Payment Risk'), ('Sales & Output GST Risk', 'Sales & Output GST Risk'), ('Purchase & ITC Risk', 'Purchase & ITC Risk'), ('Import & Transaction Risk', 'Import & Transaction Risk'), ('Refund Risk', 'Refund Risk'), ('GST Behaviour & Compliance History Risk', 'GST Behaviour & Compliance History Risk')], max_length=50, null=True, verbose_name='Risk Type')),
                ('risk_indicator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Risk Indicator')),
                ('risk_pattern', models.CharField(blank=True, max_length=100, null=True, verbose_name='Risk Pattern')),
                ('inherent_risk', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Inherent Risk (0-5)')),
                ('control_risk', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Control Risk (0-5)')),
                ('detection_risk', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Detection Risk (0-5)')),
                ('gst_behaviour_risk', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='GST Behaviour Risk (0-5)')),
                ('transaction_risk', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Transaction Risk (0-5)')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Risk Score (0-5)')),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True, verbose_name='Risk Level')),
                ('audit_assertion', models.CharField(blank=True, choices=[('A01 – Completeness', 'A01 – Completeness'), ('A02 – Occurrence', 'A02 – Occurrence'), ('A03 – Accuracy', 'A03 – Accuracy'), ('A04 – Cut-off', 'A04 – Cut-off'), ('A05 – Classification', 'A05 – Classification'), ('A06 – Existence', 'A06 – Existence'), ('A07 – Rights & Obligations', 'A07 – Rights & Obligations'), ('A08 – Valuation', 'A08 – Valuation'), ('A09 – Compliance', 'A09 – Compliance')], max_length=50, null=True, verbose_name='Audit Assertion')),
                ('risk_reason', models.TextField(blank=True, null=True, verbose_name='Risk Reason')),
                ('system_decision', models.CharField(blank=True, choices=[('AUDIT', 'AUDIT'), ('REVIEW', 'REVIEW'), ('MONITOR', 'MONITOR'), ('NOT SELECTED', 'NOT SELECTED')], editable=False, max_length=20, null=True, verbose_name='System Decision')),
                ('selection', models.CharField(blank=True, choices=[('AUDIT', 'AUDIT'), ('REVIEW', 'REVIEW'), ('MONITOR', 'MONITOR'), ('NOT SELECTED', 'NOT SELECTED')], editable=False, max_length=20, null=True, verbose_name='Selection (Auto-Generated)')),
                ('referred_to', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Referred To (Auto-Generated)')),
                ('prescribed_officer_action', models.TextField(blank=True, editable=False, null=True, verbose_name='Prescribed Officer Action')),
                ('officer_assessment', models.TextField(blank=True, null=True, verbose_name='Officer Assessment / Judgment')),
                ('additional_risk_factor', models.TextField(blank=True, null=True, verbose_name='Additional Risk Factor')),
                ('officer_risk_rating', models.CharField(blank=True, max_length=20, null=True, verbose_name='Officer Risk Rating')),
                ('officer_remarks', models.TextField(blank=True, null=True, verbose_name='Officer Remarks')),
                ('final_selection', models.CharField(blank=True, choices=[('AUDIT', 'AUDIT'), ('REVIEW', 'REVIEW'), ('MONITOR', 'MONITOR'), ('NOT SELECTED', 'NOT SELECTED')], max_length=20, null=True, verbose_name='Final Selection')),
                ('final_referred_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Final Referred To')),
                ('action_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Action Status')),
                ('override_reason', models.TextField(blank=True, null=True, verbose_name='Override Reason')),
                ('override_date', models.DateTimeField(blank=True, null=True, verbose_name='Override Date')),
                ('original_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Original Risk Score')),
                ('original_risk_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Original Risk Level')),
                ('original_selection', models.CharField(blank=True, max_length=20, null=True, verbose_name='Original Selection')),
                ('original_system_decision', models.CharField(blank=True, max_length=20, null=True, verbose_name='Original System Decision')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Overridden By')),
            ],
            options={
                'verbose_name': 'Compliance Risk & Referral',
                'verbose_name_plural': 'Compliance Risk & Referral',
                'ordering': ['-assessment_date', 'assessment_from_period', 'taxpayer_name'],
                'indexes': [models.Index(fields=['gstin', 'assessment_from_period'], name='compliance__gstin_cc873c_idx'), models.Index(fields=['assessment_from_period'], name='compliance__assessm_9113e8_idx'), models.Index(fields=['assessment_to_period'], name='compliance__assessm_4aafac_idx'), models.Index(fields=['risk_level'], name='compliance__risk_le_31d5eb_idx'), models.Index(fields=['risk_type'], name='compliance__risk_ty_76fec5_idx'), models.Index(fields=['system_decision'], name='compliance__system__43b9f0_idx'), models.Index(fields=['final_selection'], name='compliance__final_s_ae3942_idx'), models.Index(fields=['assessment_status'], name='compliance__assessm_8b1a82_idx')],
                'unique_together': {('gstin', 'assessment_from_period', 'assessment_to_period')},
            },
        ),
    ]
