# Generated by Django 6.1 on 2026-08-14 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceriskreferral',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audits', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Officer'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assignment Date'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='assignment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True, verbose_name='Assignment Status'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='officer_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Officer Comments'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='officer_recommendation',
            field=models.CharField(blank=True, choices=[('Proceed with Audit', 'Proceed with Audit'), ('Monitor Only', 'Monitor Only'), ('No Action Required', 'No Action Required')], max_length=50, null=True, verbose_name='Officer Recommendation'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='officer_recommendation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Officer Recommendation Date'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='section_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_head_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Section Head'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='section_head_approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True, verbose_name='Section Head Approval'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='section_head_review',
            field=models.TextField(blank=True, null=True, verbose_name='Section Head Review Comments'),
        ),
        migrations.AddField(
            model_name='complianceriskreferral',
            name='section_head_review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Section Head Review Date'),
        ),
    ]
