# Generated by Django 6.1 on 2026-08-07 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('returns', '0004_alter_gstreturn_compliance_status_and_more'),
        ('taxpayers', '0011_alter_taxpayermaster_dzongkhag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='compliancemonitoring',
            name='compliance__taxpaye_e581b3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='compliancemonitoring',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='compliancemonitoring',
            name='assessment_from',
            field=models.DateField(blank=True, null=True, verbose_name='Assessment From Date'),
        ),
        migrations.AddField(
            model_name='compliancemonitoring',
            name='assessment_to',
            field=models.DateField(blank=True, null=True, verbose_name='Assessment To Date'),
        ),
        migrations.AddIndex(
            model_name='compliancemonitoring',
            index=models.Index(fields=['taxpayer', 'assessment_from'], name='compliance__taxpaye_9c67c1_idx'),
        ),
        migrations.RemoveField(
            model_name='compliancemonitoring',
            name='assessment_period',
        ),
    ]
