# Generated by Django 6.1 on 2026-08-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_remove_compliancemonitoring_compliance__taxpaye_e581b3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='compliance_score',
            field=models.IntegerField(default=0, verbose_name='Compliance Score (0-100)'),
        ),
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='filing_on_time',
            field=models.BooleanField(default=False, verbose_name='Filing On Time'),
        ),
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='notification_compliance',
            field=models.BooleanField(default=False, verbose_name='Notification Compliance'),
        ),
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='payment_on_time',
            field=models.BooleanField(default=False, verbose_name='Payment On Time'),
        ),
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='trust_score',
            field=models.IntegerField(default=0, verbose_name='Trust Score (0-100)'),
        ),
    ]
