# Generated by Django 6.1 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_compliancemonitoring_compliance_score_and_more'),
        ('taxpayers', '0011_alter_taxpayermaster_dzongkhag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemonitoring',
            name='taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_records', to='taxpayers.taxpayermaster'),
        ),
    ]
