# Generated by Django 6.1 on 2026-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_alter_compliancemonitoring_assessment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceriskreferral',
            name='assessment_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assessment Date'),
        ),
        migrations.AlterField(
            model_name='enforcementrecovery',
            name='notice_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Notice Date'),
        ),
    ]
