# Generated by Django 6.1 on 2026-08-07 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='value',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_address',
            field=models.TextField(default='Thimphu, Bhutan', verbose_name='Contact Address'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_email',
            field=models.EmailField(default='info@gst.gov.bt', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='contact_phone',
            field=models.CharField(default='+975-2-322525', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_smtp_server',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP Server'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='organization_name',
            field=models.CharField(default='Revenue and Customs Division', max_length=200, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_footer_text',
            field=models.CharField(default='GST Compliance Report', max_length=500, verbose_name='Report Footer Text'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='report_logo_url',
            field=models.URLField(blank=True, verbose_name='Report Logo URL'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_email_notifications',
            field=models.BooleanField(default=True, verbose_name='Send Email Notifications'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='GST Compliance System', max_length=200, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By'),
        ),
    ]
