# Generated by Django 6.1 on 2026-08-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_systemsettings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('section_head', 'Section Head'), ('audit_refund', 'Audit and Refund'), ('registration_enquiry', 'Registration Taxpayer Enquiry'), ('compliance', 'Compliance')], default='compliance', max_length=50),
        ),
    ]
