# Generated by Django 6.1 on 2026-08-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_compliance',
            field=models.BooleanField(default=False, verbose_name='Add Compliance'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_enforcement',
            field=models.BooleanField(default=False, verbose_name='Add Enforcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_refunds',
            field=models.BooleanField(default=False, verbose_name='Add Refunds'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_returns',
            field=models.BooleanField(default=False, verbose_name='Add GST Returns'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_taxpayers',
            field=models.BooleanField(default=False, verbose_name='Add Taxpayers'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_users',
            field=models.BooleanField(default=False, verbose_name='Add Users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_audit',
            field=models.BooleanField(default=False, verbose_name='Approve Audit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_approve_risk_assessment',
            field=models.BooleanField(default=False, verbose_name='Approve Risk Assessment'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_create_audit',
            field=models.BooleanField(default=False, verbose_name='Create Audit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_compliance',
            field=models.BooleanField(default=False, verbose_name='Delete Compliance'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_enforcement',
            field=models.BooleanField(default=False, verbose_name='Delete Enforcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_refunds',
            field=models.BooleanField(default=False, verbose_name='Delete Refunds'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_returns',
            field=models.BooleanField(default=False, verbose_name='Delete GST Returns'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_taxpayers',
            field=models.BooleanField(default=False, verbose_name='Delete Taxpayers'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_users',
            field=models.BooleanField(default=False, verbose_name='Delete Users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_audit',
            field=models.BooleanField(default=False, verbose_name='Edit Audit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_compliance',
            field=models.BooleanField(default=False, verbose_name='Edit Compliance'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_enforcement',
            field=models.BooleanField(default=False, verbose_name='Edit Enforcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_refunds',
            field=models.BooleanField(default=False, verbose_name='Edit Refunds'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_returns',
            field=models.BooleanField(default=False, verbose_name='Edit GST Returns'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_risk_assessment',
            field=models.BooleanField(default=False, verbose_name='Edit Risk Assessment'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_settings',
            field=models.BooleanField(default=False, verbose_name='Edit Settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_taxpayers',
            field=models.BooleanField(default=False, verbose_name='Edit Taxpayers'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_edit_users',
            field=models.BooleanField(default=False, verbose_name='Edit Users'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False, verbose_name='Export Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_reports',
            field=models.BooleanField(default=False, verbose_name='Export Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_generate_reports',
            field=models.BooleanField(default=False, verbose_name='Generate Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_import_data',
            field=models.BooleanField(default=False, verbose_name='Import Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_permissions',
            field=models.BooleanField(default=False, verbose_name='Manage Permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_run_risk_assessment',
            field=models.BooleanField(default=False, verbose_name='Run Risk Assessment'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_audit',
            field=models.BooleanField(default=False, verbose_name='View Audit'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_compliance',
            field=models.BooleanField(default=False, verbose_name='View Compliance'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_enforcement',
            field=models.BooleanField(default=False, verbose_name='View Enforcement'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_refunds',
            field=models.BooleanField(default=False, verbose_name='View Refunds'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='View Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_returns',
            field=models.BooleanField(default=False, verbose_name='View GST Returns'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_risk_assessment',
            field=models.BooleanField(default=False, verbose_name='View Risk Assessment'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_settings',
            field=models.BooleanField(default=False, verbose_name='View Settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_taxpayers',
            field=models.BooleanField(default=False, verbose_name='View Taxpayers'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_users',
            field=models.BooleanField(default=False, verbose_name='View Users'),
        ),
    ]
