# Generated by Django 6.1 on 2026-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='RRCO/GST Mongar Administration', max_length=200, verbose_name='System Name'),
        ),
    ]
