# Generated by Django 6.1 on 2026-08-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_systemsettings_system_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='system_name',
            field=models.CharField(default='GST Administration', max_length=200, verbose_name='System Name'),
        ),
    ]
