"""
Django settings for gst_compliance_system project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv not installed, will use system environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-#k9q!2@f$8m@z^x#v7b$n5c%q3w@e$r6t*y8u&i0o')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Add Render.com domain automatically if not present
if 'ON_RENDER' in os.environ:
    render_domain = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
    if render_domain and render_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_domain)
        ALLOWED_HOSTS.append(f'.{render_domain}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'import_export',
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    # Local apps - ordered as requested for admin panel
    'core',              # 1) Core (Authentication and Authorization)
    'taxpayers',         # 2) Registration and Enquiry
    'returns',           # 3) Returns
    'compliance',        # 4) Compliance & Enforcement Module
    'audit_refund',      # 5) Audit & Refund Module (includes Refund Register admin)
    'reporting',         # 6) Reporting
    'refunds',           # Data models only - added last but will be hidden from admin
]

# Custom admin ordering without creating custom admin site
# This will be applied in urls.py to avoid circular imports

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add Whitenoise for static files
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.security_middleware.SecurityMiddleware',  # Custom security middleware
    'core.security_middleware.PermissionMiddleware',  # Custom permission middleware
]

ROOT_URLCONF = 'gst_compliance_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gst_compliance_system.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'core.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'core.authentication.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication for all API endpoints
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# CORS Configuration - RESTRICTED FOR SECURITY
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False  # SECURITY: Disabled - only allow specific origins


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Thimphu'  # Bhutan time zone
USE_I18N = True
USE_TZ = False  # Disable timezone to avoid date conversion issues

# Date formats - dd-mm-yyyy with leading zeros
DATE_FORMAT = 'd-m-Y'
DATETIME_FORMAT = 'd-m-Y H:i:s'
SHORT_DATE_FORMAT = 'd-m-Y'
SHORT_DATETIME_FORMAT = 'd-m-Y H:i:s'

# Month-Year format for tax periods - Jan-2026 format
MONTH_YEAR_FORMAT = 'M-Y'

# Ensure all date fields use this format
USE_L10N = False  # Disable localization to ensure consistent date formatting


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Whitenoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'gst-compliance@system.local'

# Security settings for development
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Admin settings
ADMIN_SHOW_FULL_RESULT_COUNT = True

# Django Jet Reboot Configuration
JET_DEFAULT_THEME = 'default'
JET_THEMES = [
    {
        'theme': 'default',
        'display_name': 'Default',
        'user_switch_theme': True,
        'copy': True,
    },
    {
        'theme': 'green',
        'display_name': 'Green',
        'user_switch_theme': True,
        'copy': True,
    },
    {
        'theme': 'light-green',
        'display_name': 'Light Green',
        'user_switch_theme': True,
        'copy': True,
    },
    {
        'theme': 'light-violet',
        'display_name': 'Light Violet',
        'user_switch_theme': True,
        'copy': True,
    },
    {
        'theme': 'light-blue',
        'display_name': 'Light Blue',
        'user_switch_theme': True,
        'copy': True,
    },
    {
        'theme': 'light-gray',
        'display_name': 'Light Gray',
        'user_switch_theme': True,
        'copy': True,
    },
]