# Generated by Django 6.1 on 2026-08-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period (e.g., Jan-2026)')),
                ('return_due_date', models.DateField(verbose_name='Return Due Date')),
                ('return_filing_date', models.DateField(blank=True, null=True, verbose_name='Return Filing Date')),
                ('filing_delay_days', models.IntegerField(default=0, verbose_name='Filing Delay (Days)')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('dzongkhag', models.CharField(max_length=100, verbose_name='Dzongkhag')),
                ('organisation_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, verbose_name='Frequency')),
                ('declared_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Sales')),
                ('declared_domestic_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Domestic Purchase/Taxable Expenses')),
                ('declared_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Import Value')),
                ('ecms_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='eCMS Import Value')),
                ('declared_import_gst', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Import GST')),
                ('domestic_purchase_itc_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Domestic Purchase ITC Claimed')),
                ('total_itc_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total ITC Claimed')),
                ('declared_output_gst', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Output GST')),
                ('gst_payable_refundable', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST Payable / Refundable (GST Return)')),
                ('actual_gst_payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Actual GST Payment Received')),
                ('bank_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bank Deposits')),
                ('filing_status', models.CharField(choices=[('filed', 'Filed'), ('not_filed', 'Not Filed'), ('late_filed', 'Late Filed'), ('revised', 'Revised'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Filing Status')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit'), ('pending', 'Pending'), ('partial', 'Partial Payment')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('late_filer', 'Late Filer'), ('non_compliant', 'Non-Compliant'), ('under_review', 'Under Review')], default='under_review', max_length=20, verbose_name='Compliance Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Return',
                'verbose_name_plural': 'GST Returns',
                'ordering': ['-tax_period', 'taxpayer_name'],
                'indexes': [models.Index(fields=['gstin', 'tax_period'], name='returns_gst_gstin_2c0208_idx'), models.Index(fields=['tax_period'], name='returns_gst_tax_per_1c2555_idx'), models.Index(fields=['filing_status'], name='returns_gst_filing__2e8cdb_idx'), models.Index(fields=['compliance_status'], name='returns_gst_complia_b5c0db_idx')],
                'unique_together': {('gstin', 'tax_period')},
            },
        ),
        migrations.CreateModel(
            name='NotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('organisation_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type')),
                ('return_period', models.CharField(max_length=20, verbose_name='Return Period')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('credit', 'Credit'), ('pending', 'Pending'), ('partial', 'Partial Payment')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('filing_status', models.CharField(choices=[('not_filed', 'Not Filed'), ('filed_late', 'Filed Late'), ('pending', 'Pending')], default='not_filed', max_length=20, verbose_name='Filing Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notfiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Not File',
                'verbose_name_plural': 'Not Files',
                'ordering': ['-return_period', 'taxpayer_name'],
                'indexes': [models.Index(fields=['gstin', 'return_period'], name='returns_not_gstin_ecdd0c_idx'), models.Index(fields=['return_period'], name='returns_not_return__eb6c34_idx'), models.Index(fields=['filing_status'], name='returns_not_filing__be5d8c_idx')],
                'unique_together': {('gstin', 'return_period')},
            },
        ),
    ]
