# Generated by Django 6.1 on 2026-08-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(choices=[('compliant', 'Compliant'), ('late_filer', 'Late Filer'), ('late_payment', 'Late Payment'), ('non_filer', 'Non-Filer'), ('return_amended', 'Return Amended'), ('under_review', 'Under Review')], default='under_review', max_length=20, verbose_name='Compliance Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('not_filed', 'Not Filed'), ('extension', 'Extension'), ('due', 'Due'), ('over_due', 'Over Due')], default='pending', max_length=20, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('credit', 'Credit'), ('zero_return', 'Zero Return'), ('reconciled', 'Reconciled Output Input')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
    ]
