# Generated by Django 6.1 on 2026-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_alter_gstreturn_compliance_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gstreturn',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='actual_gst_payment_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Actual GST Payment Received'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='bank_deposits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Bank Deposits'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('late_filer', 'Late Filer'), ('late_payment', 'Late payment'), ('non_filer', 'Non-Filer'), ('return_amended', 'Return Amended'), ('under_review', 'Under Review')], max_length=20, null=True, verbose_name='Compliance Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='declared_domestic_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Declared Domestic Purchase/Taxable Expenses'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='declared_import_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Declared Import GST'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='declared_import_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Declared Import Value'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='declared_output_gst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Declared Output GST'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='declared_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Declared Sales'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='domestic_purchase_itc_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Domestic Purchase ITC Claimed'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='ecms_import_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='eCMS Import Value'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('filed', 'Filed'), ('not_filed', 'Not Filed'), ('extension', 'Extention'), ('due', 'Due'), ('over_due', 'Over Due')], max_length=20, null=True, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='gst_payable_refundable',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='GST Payable / Refundable (GST Return)'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, null=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('not_paid', 'Not paid'), ('credit', 'Credit'), ('zero_return', 'Zero Return'), ('reconciled', 'Reconciled Output Input')], max_length=20, null=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='return_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Return Due Date'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='taxpayer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxpayer Name'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='total_itc_claimed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Total ITC Claimed'),
        ),
    ]
