# Generated by Django 6.1 on 2026-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_alter_gstreturn_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('Compliant', 'Compliant'), ('late_filer', 'Late Filer'), ('late_payment', 'Late payment'), ('non_filer', 'Non-Filer'), ('return_amended', 'Return Amended'), ('under_review', 'Under Review')], max_length=20, null=True, verbose_name='Compliance Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('filed', 'Filed'), ('Filed', 'Filed'), ('not_filed', 'Not Filed'), ('Not Filed', 'Not Filed'), ('extension', 'Extention'), ('Extention', 'Extention'), ('Extension', 'Extension'), ('due', 'Due'), ('over_due', 'Over Due')], max_length=20, null=True, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('Paid', 'Paid'), ('not_paid', 'Not paid'), ('Not paid', 'Not paid'), ('credit', 'Credit'), ('zero_return', 'Zero Return'), ('reconciled', 'Reconciled Output Input')], max_length=20, null=True, verbose_name='Payment Status'),
        ),
    ]
