# Generated by Django 6.1 on 2026-08-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_alter_gstreturn_compliance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfile',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
    ]
