# Generated by Django 6.1 on 2026-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_alter_gstreturn_compliance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('Compliant', 'Compliant'), ('late_filer', 'Late Filer'), ('late_payment', 'Late payment'), ('non_filer', 'Non-Filer'), ('return_amended', 'Return Amended'), ('under_review', 'Under Review')], max_length=20, null=True, verbose_name='Compliance Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('filed', 'Filed'), ('Filed', 'Filed'), ('not_filed', 'Not Filed'), ('Not Filed', 'Not Filed'), ('extension', 'Extention'), ('Extention', 'Extention'), ('Extension', 'Extension'), ('due', 'Due'), ('over_due', 'Over Due')], max_length=20, null=True, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, null=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('Paid', 'Paid'), ('not_paid', 'Not paid'), ('Not paid', 'Not paid'), ('credit', 'Credit'), ('zero_return', 'Zero Return'), ('reconciled', 'Reconciled Output Input')], max_length=20, null=True, verbose_name='Payment Status'),
        ),
    ]
