# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0007_alter_gstreturn_compliance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_delay_days',
            field=models.IntegerField(default=0, null=True, blank=True, verbose_name='Filing Delay (Days)'),
        ),
    ]