# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0008_auto_20260808_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20, null=True, blank=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='organisation_type',
            field=models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('Limited Liability Partnership', 'Limited Liability Partnership'), ('Trust', 'Trust'), ('Government Entity', 'Government Entity'), ('Other', 'Other')], max_length=30, null=True, blank=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='dzongkhag',
            field=models.CharField(choices=[('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuentse', 'Lhuentse')], max_length=100, null=True, blank=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(choices=[('Filed', 'Filed'), ('Not Filed', 'Not Filed'), ('Extension', 'Extension'), ('Due', 'Due'), ('Over Due', 'Over Due')], max_length=20, null=True, blank=True, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not paid', 'Not paid'), ('Credit', 'Credit'), ('Zero Return', 'Zero Return'), ('Reconciled Output Input', 'Reconciled Output Input')], max_length=30, null=True, blank=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Late Filer', 'Late Filer'), ('Late payment', 'Late payment'), ('Non-Filer', 'Non-Filer'), ('Return Amended', 'Return Amended'), ('Under Review', 'Under Review')], max_length=30, null=True, blank=True, verbose_name='Compliance Status'),
        ),
    ]