# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0009_auto_20260808_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfile',
            name='filing_status',
            field=models.CharField(choices=[('', '---------'), ('Not Filed', 'Not Filed'), ('Filed Late', 'Filed Late'), ('Pending', 'Pending')], default='Not Filed', max_length=20, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='notfile',
            name='payment_status',
            field=models.CharField(choices=[('', '---------'), ('Paid', 'Paid'), ('Credit', 'Credit'), ('Pending', 'Pending'), ('Partial Payment', 'Partial Payment')], default='Pending', max_length=20, verbose_name='Payment Status'),
        ),
    ]