# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0010_auto_20260808_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfile',
            name='dzongkhag',
            field=models.CharField(choices=[('', '---------'), ('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuentse', 'Lhuentse')], max_length=100, null=True, blank=True, verbose_name='Dzongkhag'),
        ),
    ]