# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0011_auto_20260808_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='organisation_type',
            field=models.CharField(choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, null=True, blank=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='notfile',
            name='organisation_type',
            field=models.CharField(choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, verbose_name='Organisation Type'),
        ),
    ]