# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0012_auto_20260808_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(choices=[('Filed On Time', 'Filed On Time'), ('Late Filer', 'Late Filer'), ('Due', 'Due'), ('Overdue / Non-Filer', 'Overdue / Non-Filer'), ('Extension', 'Extension')], max_length=20, null=True, blank=True, verbose_name='Filing Status'),
        ),
    ]