# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0013_auto_20260808_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Late Filer', 'Late Filer'), ('Non-Filer', 'Non-Filer'), ('Pending', 'Pending'), ('Inactive Taxpayer', 'Inactive Taxpayer'), ('Unknown Taxpayer', 'Unknown Taxpayer')], max_length=30, null=True, blank=True, verbose_name='Compliance Status'),
        ),
        migrations.AddField(
            model_name='notfile',
            name='compliance_status',
            field=models.CharField(choices=[('Compliant', 'Compliant'), ('Late Filer', 'Late Filer'), ('Non-Filer', 'Non-Filer'), ('Pending', 'Pending'), ('Inactive Taxpayer', 'Inactive Taxpayer'), ('Unknown Taxpayer', 'Unknown Taxpayer')], max_length=30, null=True, blank=True, verbose_name='Compliance Status'),
        ),
        migrations.AlterField(
            model_name='notfile',
            name='filing_status',
            field=models.CharField(choices=[('', '---------'), ('Filed On Time', 'Filed On Time'), ('Late Filer', 'Late Filer'), ('Due', 'Due'), ('Overdue / Non-Filer', 'Overdue / Non-Filer'), ('Extension', 'Extension')], default='Overdue / Non-Filer', max_length=20, verbose_name='Filing Status'),
        ),
    ]