# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0014_auto_20260808_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfile',
            name='filing_status',
            field=models.CharField(choices=[('', '---------'), ('Filed On Time', 'Filed On Time'), ('Late Filer', 'Late Filer'), ('Due', 'Due'), ('Overdue / Non-Filer', 'Overdue / Non-Filer'), ('Extension', 'Extension')], default='Overdue / Non-Filer', max_length=20, verbose_name='Filing Status'),
        ),
    ]