# Generated by Django 6.1 on 2026-08-08 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0015_auto_20260808_2145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfile',
            name='filing_status',
            field=models.CharField(choices=[('Filed On Time', 'Filed On Time'), ('Late Filer', 'Late Filer'), ('Due', 'Due'), ('Overdue / Non-Filer', 'Overdue / Non-Filer'), ('Extension', 'Extension')], default='Overdue / Non-Filer', max_length=20, verbose_name='Filing Status'),
        ),
        migrations.AddIndex(
            model_name='notfile',
            index=models.Index(fields=['compliance_status'], name='returns_not_complia_b04592_idx'),
        ),
    ]
