# Generated by Django 6.1 on 2026-08-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0016_alter_notfile_filing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='tax_period',
            field=models.CharField(max_length=20, verbose_name='Tax Period'),
        ),
    ]
