# Generated by Django 6.1 on 2026-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0017_alter_gstreturn_tax_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='tax_period',
            field=models.CharField(choices=[('Jan-2026', 'Jan-2026'), ('Feb-2026', 'Feb-2026'), ('Mar-2026', 'Mar-2026'), ('Apr-2026', 'Apr-2026'), ('May-2026', 'May-2026'), ('Jun-2026', 'Jun-2026'), ('Jul-2026', 'Jul-2026'), ('Aug-2026', 'Aug-2026'), ('Sep-2026', 'Sep-2026'), ('Oct-2026', 'Oct-2026'), ('Nov-2026', 'Nov-2026'), ('Dec-2026', 'Dec-2026'), ('Jan-2027', 'Jan-2027'), ('Feb-2027', 'Feb-2027'), ('Mar-2027', 'Mar-2027'), ('Apr-2027', 'Apr-2027'), ('May-2027', 'May-2027'), ('Jun-2027', 'Jun-2027'), ('Jul-2027', 'Jul-2027'), ('Aug-2027', 'Aug-2027'), ('Sep-2027', 'Sep-2027'), ('Oct-2027', 'Oct-2027'), ('Nov-2027', 'Nov-2027'), ('Dec-2027', 'Dec-2027')], max_length=20, verbose_name='Tax Period'),
        ),
    ]
