# Generated by Django 6.1 on 2026-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0018_alter_gstreturn_tax_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='filing_status',
            field=models.CharField(blank=True, choices=[('Filed', 'Filed'), ('Overdue / Non-Filer', 'Overdue / Non-Filer'), ('Late Filer', 'Late Filer'), ('Pending', 'Pending')], max_length=20, null=True, verbose_name='Filing Status'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Not paid', 'Not paid'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending')], max_length=30, null=True, verbose_name='Payment Status'),
        ),
    ]
