# Generated by Django 6.1 on 2026-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0019_alter_gstreturn_filing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='tax_period',
            field=models.CharField(choices=[('Jan-2026', 'Jan-2026'), ('Feb-2026', 'Feb-2026'), ('Mar-2026', 'Mar-2026'), ('Apr-2026', 'Apr-2026'), ('May-2026', 'May-2026'), ('Jun-2026', 'Jun-2026'), ('Jul-2026', 'Jul-2026'), ('Aug-2026', 'Aug-2026'), ('Sep-2026', 'Sep-2026'), ('Oct-2026', 'Oct-2026'), ('Nov-2026', 'Nov-2026'), ('Dec-2026', 'Dec-2026')], max_length=20, verbose_name='Tax Period'),
        ),
    ]
