# Generated by Django 6.1 on 2026-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0020_alter_gstreturn_tax_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='tax_period',
            field=models.CharField(max_length=20, verbose_name='Tax Period'),
        ),
    ]
