# Generated by Django 6.1 on 2026-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0021_alter_gstreturn_tax_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreturn',
            name='return_due_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Return Due Date'),
        ),
        migrations.AlterField(
            model_name='gstreturn',
            name='return_filing_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Return Filing Date'),
        ),
    ]
