# Generated by Django 6.1 on 2026-08-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxpayerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid_company_reg_no', models.CharField(max_length=50, verbose_name='CID No/Co. Reg No')),
                ('gstin', models.CharField(max_length=15, unique=True, verbose_name='GSTIN')),
                ('ramis_tpn', models.CharField(blank=True, max_length=50, verbose_name='RAMIS TPN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Business Name')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('sub_sector', models.CharField(blank=True, max_length=100, verbose_name='Sub-Sector')),
                ('business_activity', models.CharField(blank=True, max_length=200, verbose_name='Business Activity')),
                ('organisation_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, verbose_name='Frequency')),
                ('dzongkhag', models.CharField(max_length=100, verbose_name='Dzongkhag')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('commencement_date', models.DateField(blank=True, null=True, verbose_name='Commencement Date')),
                ('deregistration_date', models.DateField(blank=True, null=True, verbose_name='Deregistration Date')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='Mobile Number')),
                ('business_address', models.TextField(blank=True, verbose_name='Business Address')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_taxpayers_master', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_taxpayers_master', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taxpayer Master',
                'verbose_name_plural': 'Taxpayer Masters',
                'ordering': ['taxpayer_name'],
                'indexes': [models.Index(fields=['gstin'], name='taxpayers_t_gstin_554c0d_idx'), models.Index(fields=['cid_company_reg_no'], name='taxpayers_t_cid_com_b8ebe3_idx'), models.Index(fields=['ramis_tpn'], name='taxpayers_t_ramis_t_e64fa0_idx'), models.Index(fields=['taxpayer_name'], name='taxpayers_t_taxpaye_5f8a1b_idx'), models.Index(fields=['dzongkhag'], name='taxpayers_t_dzongkh_a6dcf4_idx'), models.Index(fields=['status'], name='taxpayers_t_status_df6b00_idx')],
            },
        ),
    ]
