# Generated by Django 6.1 on 2026-08-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='business_address',
            field=models.TextField(blank=True, null=True, verbose_name='Business Address'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='cid_company_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CID No/Co. Reg No'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='ramis_tpn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RAMIS TPN'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
