# Generated by Django 6.1 on 2026-08-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0002_alter_taxpayermaster_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='gstin',
            field=models.CharField(max_length=15, verbose_name='GSTIN'),
        ),
    ]
