# Generated by Django 6.1 on 2026-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0003_alter_taxpayermaster_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('Monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('Quarterly', 'Quarterly'), ('annual', 'Annual'), ('Annual', 'Annual')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='organisation_type',
            field=models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('Sole Proprietorship', 'Sole Proprietorship'), ('sole Proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('Private Company', 'Private Company'), ('public_company', 'Public Company'), ('Public Company', 'Public Company'), ('partnership', 'Partnership'), ('Partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('Foreign Company', 'Foreign Company'), ('Joint Venture', 'Joint Venture'), ('State Owned Company', 'State Owned Company'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('Active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('Deregistered', 'Deregistered')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
