# Generated by Django 6.1 on 2026-08-06 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0006_taxpayermaster_is_primary_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayermaster',
            name='primary_taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_licenses', to='taxpayers.taxpayermaster', verbose_name='Primary Taxpayer'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('Monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('Quarterly', 'Quarterly'), ('annual', 'Annual'), ('Annual', 'Annual')], max_length=50, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('Sole Proprietorship', 'Sole Proprietorship'), ('sole_proprietor', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('Private Company', 'Private Company'), ('public_company', 'Public Company'), ('Public Company', 'Public Company'), ('partnership', 'Partnership'), ('Partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('Limited Liability Partnership', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('Government Entity', 'Government Entity'), ('foreign_company', 'Foreign Company'), ('Foreign Company', 'Foreign Company'), ('joint_venture', 'Joint Venture'), ('Joint Venture', 'Joint Venture'), ('state_owned_company', 'State Owned Company'), ('State Owned Company', 'State Owned Company'), ('other', 'Other'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('Active', 'Active'), ('inactive', 'Inactive'), ('Inactive', 'Inactive'), ('suspended', 'Suspended'), ('Suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('Cancelled', 'Cancelled'), ('deregistered', 'Deregistered'), ('Deregistered', 'Deregistered')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
