# Generated by Django 6.1 on 2026-08-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0007_taxpayermaster_primary_taxpayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLicense',
            fields=[
            ],
            options={
                'verbose_name': 'Additional License',
                'verbose_name_plural': 'Additional Licenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taxpayers.taxpayermaster',),
        ),
    ]
