# Generated by Django 6.1 on 2026-08-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0010_alter_taxpayermaster_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('thimphu', 'Thimphu'), ('paro', 'Paro'), ('punakha', 'Punakha'), ('wangdue_phodrang', 'Wangdue Phodrang'), ('tsirang', 'Tsirang'), ('dagana', 'Dagana'), ('chukha', 'Chukha'), ('haa', 'Haa'), ('samtse', 'Samtse'), ('sarpang', 'Sarpang'), ('trashigang', 'Trashigang'), ('mongar', 'Mongar'), ('pemagatshel', 'Pemagatshel'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse'), ('bumthang', 'Bumthang'), ('zhemgang', 'Zhemgang'), ('trongsa', 'Trongsa'), ('sarpang', 'Sarpang'), ('gasa', 'Gasa')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
    ]
