# Generated by Django 6.1 on 2026-08-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0011_alter_taxpayermaster_dzongkhag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
    ]
