# Generated by Django 6.1 on 2026-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0012_alter_taxpayermaster_dzongkhag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('', '---------'), ('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', '---------'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly')], max_length=50, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('government', 'Government Entity'), ('foreign_company', 'Foreign Company'), ('joint_venture', 'Joint Venture'), ('state_owned_company', 'State Owned Company'), ('other', 'Other')], max_length=50, null=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('deregistered', 'Deregistered')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
