# Generated by Django 6.1 on 2026-08-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0013_alter_taxpayermaster_dzongkhag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('government', 'Government Entity'), ('foreign_company', 'Foreign Company'), ('joint_venture', 'Joint Venture'), ('state_owned_company', 'State Owned Company'), ('other', 'Other')], max_length=50, null=True, verbose_name='Organisation Type'),
        ),
    ]
