# Generated by Django 6.1 on 2026-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0014_alter_taxpayermaster_organisation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly')], max_length=50, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('Government Entity', 'Government Entity'), ('Foreign Company', 'Foreign Company'), ('Joint Venture', 'Joint Venture'), ('State Owned Company', 'State Owned Company'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Deregistered', 'Deregistered')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
