# Generated by Django 6.1 on 2026-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0015_alter_taxpayermaster_dzongkhag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='taxpayer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxpayer Name'),
        ),
    ]
