# Generated by Django 6.1 on 2026-08-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0016_alter_taxpayermaster_taxpayer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalLicense',
        ),
        migrations.RemoveField(
            model_name='taxpayermaster',
            name='primary_taxpayer',
        ),
    ]
