# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0017_delete_additionallicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayermaster',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Name'),
        ),
    ]