# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0018_auto_20260808_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleLicenseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid_company_reg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='CID No/Co. Reg No')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN')),
                ('ramis_tpn', models.CharField(blank=True, max_length=50, null=True, verbose_name='RAMIS TPN')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='License Number')),
                ('taxpayer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxpayer Name')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Name')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('sub_sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Sector')),
                ('business_activity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Activity')),
                ('organisation_type', models.CharField(blank=True, choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('Government Entity', 'Government Entity'), ('Foreign Company', 'Foreign Company'), ('Joint Venture', 'Joint Venture'), ('State Owned Company', 'State Owned Company'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Organisation Type')),
                ('frequency', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly')], max_length=50, null=True, verbose_name='Frequency')),
                ('dzongkhag', models.CharField(blank=True, choices=[('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuentse', 'Lhuentse')], max_length=100, null=True, verbose_name='Dzongkhag')),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Deregistered', 'Deregistered')], max_length=50, null=True, verbose_name='Status')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Registration Date')),
                ('commencement_date', models.DateField(blank=True, null=True, verbose_name='Commencement Date')),
                ('deregistration_date', models.DateField(blank=True, null=True, verbose_name='Deregistration Date')),
                ('email_address', models.EmailField(blank=True, null=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('business_address', models.TextField(blank=True, null=True, verbose_name='Business Address')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Multiple License Reference',
                'verbose_name_plural': 'Multiple License References',
                'indexes': [
                    models.Index(fields=['gstin'], name='taxpayer_master_gstin_idx'),
                    models.Index(fields=['license_number'], name='taxpayer_master_license_idx'),
                    models.Index(fields=['taxpayer_name'], name='taxpayer_master_name_idx'),
                ],
                'ordering': ['taxpayer_name'],
            },
        ),
    ]