# Generated by Django 6.1 on 2026-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0019_auto_20260808_1654'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='multiplelicensereference',
            new_name='taxpayers_m_gstin_1625b7_idx',
            old_name='taxpayer_master_gstin_idx',
        ),
        migrations.RenameIndex(
            model_name='multiplelicensereference',
            new_name='taxpayers_m_license_b6ac8d_idx',
            old_name='taxpayer_master_license_idx',
        ),
        migrations.RenameIndex(
            model_name='multiplelicensereference',
            new_name='taxpayers_m_taxpaye_7f340e_idx',
            old_name='taxpayer_master_name_idx',
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuentse', 'Lhuentse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
    ]
