# Generated by Django 6.1 on 2026-08-12 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0020_rename_taxpayer_master_gstin_idx_taxpayers_m_gstin_1625b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplelicensereference',
            options={'ordering': ['taxpayer_name'], 'verbose_name': 'Secondary License', 'verbose_name_plural': 'Secondary Licenses'},
        ),
        migrations.AlterModelOptions(
            name='taxpayermaster',
            options={'ordering': ['taxpayer_name'], 'verbose_name': 'Primary Taxpayer', 'verbose_name_plural': 'Primary Taxpayers'},
        ),
        migrations.CreateModel(
            name='TaxpayerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_type', models.CharField(choices=[('General', 'General'), ('Registration', 'Registration'), ('Compliance', 'Compliance'), ('Returns', 'Returns'), ('Refund', 'Refund'), ('Other', 'Other')], default='General', max_length=50, verbose_name='Enquiry Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('description', models.TextField(verbose_name='Description')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxpayer Name')),
                ('cid_company_reg_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='CID/Company Reg No')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20, verbose_name='Priority')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Resolved Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Taxpayer Enquiry',
                'verbose_name_plural': 'Taxpayer Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gstin'], name='taxpayers_t_gstin_e87140_idx'), models.Index(fields=['status'], name='taxpayers_t_status_e9e2eb_idx'), models.Index(fields=['enquiry_type'], name='taxpayers_t_enquiry_3aac44_idx'), models.Index(fields=['created_at'], name='taxpayers_t_created_e17362_idx')],
            },
        ),
    ]
