# Generated by Django 6.1 on 2026-08-12 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0021_alter_multiplelicensereference_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxpayerenquiry',
            options={'ordering': ['-enquiry_date', '-created_at'], 'verbose_name': 'Taxpayer Enquiry', 'verbose_name_plural': 'Taxpayer Enquiries'},
        ),
        migrations.RemoveField(
            model_name='taxpayerenquiry',
            name='description',
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='action_response',
            field=models.TextField(blank=True, null=True, verbose_name='Action/Response'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='enquiry_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='enquiry_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Enquiry ID'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='mode',
            field=models.CharField(blank=True, choices=[('Letter', 'Letter'), ('Email', 'Email'), ('Phone', 'Phone'), ('In Person', 'In Person'), ('BITs', 'BITs'), ('Official Letter', 'Official Letter'), ('Social Media', 'Social Media'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='received_from_sent_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Received From/Sent To'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference No.'),
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='taxpayerenquiry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to=settings.AUTH_USER_MODEL, verbose_name='Officer'),
        ),
        migrations.AlterField(
            model_name='taxpayerenquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('Taxpayer Enquiry', 'Taxpayer Enquiry'), ('General Correspondence', 'General Correspondence'), ('Notice', 'Notice'), ('Assessment', 'Assessment'), ('Audit', 'Audit'), ('Refund', 'Refund'), ('ITC', 'ITC'), ('Registration', 'Registration'), ('Payment', 'Payment'), ('Return Filing', 'Return Filing'), ('Other', 'Other')], default='Taxpayer Enquiry', max_length=50, verbose_name='Enquiry Type'),
        ),
        migrations.AlterField(
            model_name='taxpayerenquiry',
            name='status',
            field=models.CharField(choices=[('Pending Taxpayer', 'Pending Taxpayer'), ('Pending Officer', 'Pending Officer'), ('Referred', 'Referred'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending Taxpayer', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='taxpayerenquiry',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject/Issue'),
        ),
        migrations.AddIndex(
            model_name='taxpayerenquiry',
            index=models.Index(fields=['enquiry_id'], name='taxpayers_t_enquiry_88d673_idx'),
        ),
        migrations.AddIndex(
            model_name='taxpayerenquiry',
            index=models.Index(fields=['enquiry_date'], name='taxpayers_t_enquiry_e1576e_idx'),
        ),
    ]
