# Generated by Django 6.1 on 2026-08-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0023_alter_multiplelicensereference_deregistration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplelicensereference',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Deregistered', 'Deregistered'), ('Region Transferred', 'Region Transferred')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='taxpayermaster',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled'), ('Deregistered', 'Deregistered'), ('Region Transferred', 'Region Transferred')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
