# Generated by Django 6.1 on 2026-08-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0024_auto_20260812_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='social_media_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social Media Details'),
        ),
    ]
