# Generated by Django 6.1 on 2026-08-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxpayers', '0025_taxpayerenquiry_social_media_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayerenquiry',
            name='reference_no',
        ),
        migrations.AddField(
            model_name='taxpayerenquiry',
            name='other_details',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Details'),
        ),
    ]
