# Generated by Django 6.1 on 2026-08-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('compliance', 'Compliance Report'), ('compliance_risk', 'Compliance Risk Report'), ('audit_selection', 'Audit Selection Report'), ('refund_analysis', 'Refund Analysis Report'), ('taxpayer_summary', 'Taxpayer Summary Report'), ('custom', 'Custom Report')], max_length=30),
        ),
    ]
