# Generated by Django 6.1 on 2026-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reporttemplate_report_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Report Template', 'verbose_name_plural': 'Report Templates'},
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='calculations_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='category',
            field=models.CharField(choices=[('management', 'Management Reports'), ('taxpayer', 'Taxpayer Reports'), ('returns', 'GST Return & Revenue Reports'), ('compliance', 'Compliance Reports'), ('risk', 'Risk & Selection Reports'), ('audit', 'Audit Reports'), ('refund', 'Refund Reports'), ('enforcement', 'Enforcement Reports'), ('officer', 'Officer / Workload Reports'), ('custom', 'Custom Reports')], default='custom', max_length=30),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='fields_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='filters_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('management', 'Management Reports'), ('taxpayer', 'Taxpayer Reports'), ('returns', 'GST Return & Revenue Reports'), ('compliance', 'Compliance Reports'), ('risk', 'Risk & Selection Reports'), ('audit', 'Audit Reports'), ('refund', 'Refund Reports'), ('enforcement', 'Enforcement Reports'), ('officer', 'Officer / Workload Reports'), ('custom', 'Custom Reports')], max_length=30),
        ),
    ]
