# Generated by Django 6.1 on 2026-08-14 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0003_complianceriskreferral_assessor'),
        ('returns', '0018_alter_gstreturn_tax_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_case_id', models.CharField(max_length=20, unique=True, verbose_name='Audit Case ID')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('from_tax_period', models.CharField(max_length=20, verbose_name='From Tax Period')),
                ('to_tax_period', models.CharField(max_length=20, verbose_name='To Tax Period')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('dzongkhag', models.CharField(blank=True, max_length=100, verbose_name='Dzongkhag')),
                ('organisation_type', models.CharField(blank=True, max_length=50, verbose_name='Organisation Type')),
                ('frequency', models.CharField(blank=True, max_length=20, verbose_name='Frequency')),
                ('assessment_type', models.CharField(choices=[('desk_assessment', 'Desk Assessment'), ('field_audit', 'Field Audit'), ('targeted_audit', 'Targeted Audit'), ('other', 'Other')], max_length=20, verbose_name='Assessment Type')),
                ('audit_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20, verbose_name='Audit Priority')),
                ('assigned_date', models.DateField(blank=True, null=True, verbose_name='Assigned Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('referred', 'Referred'), ('pending_assignment', 'Pending Assignment'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('field_audit', 'Field Audit'), ('assessment', 'Assessment'), ('completed', 'Completed'), ('closed', 'Closed')], default='referred', max_length=20, verbose_name='Status')),
                ('case_closed_date', models.DateField(blank=True, null=True, verbose_name='Case Closed Date')),
                ('assessment_duration', models.IntegerField(blank=True, null=True, verbose_name='Assessment Duration (Days)')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_audit_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assessor')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audit_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Officer')),
                ('risk_referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compliance.complianceriskreferral', verbose_name='Risk Referral')),
            ],
            options={
                'verbose_name': 'Audit Case',
                'verbose_name_plural': 'Audit Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_no', models.CharField(max_length=20, unique=True, verbose_name='ASC No.')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('dzongkhag', models.CharField(blank=True, max_length=100, verbose_name='Dzongkhag')),
                ('organisation_type', models.CharField(blank=True, max_length=50, verbose_name='Organisation Type')),
                ('frequency', models.CharField(blank=True, max_length=20, verbose_name='Frequency')),
                ('assessment_type', models.CharField(blank=True, max_length=20, verbose_name='Assessment Type')),
                ('declared_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Declared Sales (GST Return)')),
                ('gst_on_declared_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST on Declared Sales')),
                ('declared_import_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Declared Import Value (GST Return)')),
                ('gst_on_declared_import', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST on Declared Import')),
                ('declared_domestic_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Declared Domestic Purchase & Taxable Expenses')),
                ('gst_on_declared_domestic_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST on Declared Domestic Purchase')),
                ('itc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ITC')),
                ('gst_payable_refundable_return', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST Payable / Refundable (GST Return)')),
                ('actual_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Actual Payment')),
                ('assessed_sales_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Assessed Sales Turnover')),
                ('actual_import_value_ecms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Actual Import Value (eCMS)')),
                ('assessed_import_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Assessed Import Value')),
                ('gst_on_assessed_import', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST on Assessed Import Value')),
                ('assessed_domestic_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Assessed Domestic Purchase & Taxable Expenses')),
                ('gst_on_assessed_domestic_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST on Assessed Domestic Purchase')),
                ('gst_payable_refundable_assessed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='GST Payable / Refundable (Assessed)')),
                ('variation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Variation')),
                ('variation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Variation %')),
                ('reason_code', models.CharField(blank=True, max_length=20, verbose_name='Reason Code')),
                ('discrepancy', models.TextField(blank=True, verbose_name='Discrepancy')),
                ('assessment_outcome', models.CharField(blank=True, choices=[('no_discrepancy', 'No Discrepancy'), ('adjustment_required', 'Adjustment Required'), ('additional_gst_payable', 'Additional GST Payable'), ('itc_disallowed', 'ITC Disallowed'), ('refund_adjustment', 'Refund Adjustment'), ('penalty_enforcement', 'Penalty / Enforcement Referral'), ('other', 'Other')], max_length=30, verbose_name='Assessment / Audit Outcome')),
                ('action_taken', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('adjusted', 'Adjusted'), ('itc_disallowed', 'ITC Disallowed'), ('additional_gst_assessed', 'Additional GST Assessed'), ('referred_enforcement', 'Referred for Enforcement'), ('other', 'Other')], max_length=30, verbose_name='Action Taken')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='Status')),
                ('case_closed_date', models.DateField(blank=True, null=True, verbose_name='Case Closed Date')),
                ('assessment_duration', models.IntegerField(blank=True, null=True, verbose_name='Assessment Duration (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Assessor')),
                ('gst_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.gstreturn', verbose_name='GST Return')),
                ('audit_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='audit_refund.auditcase', verbose_name='Audit Case')),
            ],
            options={
                'verbose_name': 'Audit Assessment',
                'verbose_name_plural': 'Audit Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=20, unique=True, verbose_name='Finding ID')),
                ('reason_code', models.CharField(blank=True, max_length=20, verbose_name='Reason Code')),
                ('finding_type', models.CharField(choices=[('under_declared_sales', 'Under-declared Sales'), ('incorrect_itc', 'Incorrect ITC'), ('import_discrepancy', 'Import Discrepancy'), ('incorrect_gst_calculation', 'Incorrect GST Calculation'), ('non_filing', 'Non-Filing'), ('non_payment', 'Non-Payment'), ('other', 'Other')], max_length=30, verbose_name='Finding Type')),
                ('discrepancy', models.TextField(blank=True, verbose_name='Discrepancy')),
                ('amount_involved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount Involved')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action Taken')),
                ('auditor_remarks', models.TextField(blank=True, verbose_name='Auditor Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit_refund.auditcase', verbose_name='Audit Case')),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=20, unique=True, verbose_name='Refund ID')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period')),
                ('claim_date', models.DateField(verbose_name='Claim Date')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Claimed Amount')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Adjustment')),
                ('refund_disallowed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Refund Disallowed')),
                ('refund_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Refund Approved')),
                ('refund_adjustment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Refund Adjustment %')),
                ('processing_days', models.IntegerField(blank=True, null=True, verbose_name='Processing Days')),
                ('processed_date', models.DateField(blank=True, null=True, verbose_name='Processed Date')),
                ('status', models.CharField(choices=[('application_received', 'Application Received'), ('under_review', 'Under Review'), ('verification', 'Verification'), ('adjustment_required', 'Adjustment Required'), ('approved', 'Approved'), ('partially_approved', 'Partially Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='application_received', max_length=30, verbose_name='Status')),
                ('refund_reason', models.TextField(blank=True, verbose_name='Refund Reason')),
                ('reason_code', models.CharField(blank=True, max_length=20, verbose_name='Reason Code')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_refund.auditcase', verbose_name='Audit Case')),
                ('gst_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='returns.gstreturn', verbose_name='GST Return')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('risk_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.complianceriskreferral', verbose_name='Risk Referral')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['audit_case_id'], name='audit_refun_audit_c_a1926d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['gstin'], name='audit_refun_gstin_a9e081_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['status'], name='audit_refun_status_e9b3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['assigned_officer'], name='audit_refun_assigne_6f5971_idx'),
        ),
        migrations.AddIndex(
            model_name='auditcase',
            index=models.Index(fields=['from_tax_period'], name='audit_refun_from_ta_067ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditassessment',
            index=models.Index(fields=['asc_no'], name='audit_refun_asc_no_982a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditassessment',
            index=models.Index(fields=['audit_case'], name='audit_refun_audit_c_4b7367_idx'),
        ),
        migrations.AddIndex(
            model_name='auditassessment',
            index=models.Index(fields=['gstin'], name='audit_refun_gstin_710c97_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['finding_id'], name='audit_refun_finding_028c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit_case'], name='audit_refun_audit_c_618936_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_id'], name='audit_refun_refund__cb6b48_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['gstin'], name='audit_refun_gstin_43072d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tax_period'], name='audit_refun_tax_per_b2bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='audit_refun_status_dd551b_idx'),
        ),
    ]
