# Generated by Django 6.1 on 2026-08-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_refund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='refund',
            name='audit_refun_refund__cb6b48_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='audit_refun_gstin_43072d_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='audit_refun_tax_per_b2bd31_idx',
        ),
        migrations.RemoveIndex(
            model_name='refund',
            name='audit_refun_status_dd551b_idx',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
