# Generated by Django 6.1 on 2026-08-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_refund', '0003_refundregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditassessment',
            name='assessment_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assessment Date'),
        ),
        migrations.AlterField(
            model_name='auditassessment',
            name='case_closed_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Case Closed Date'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='assessment_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assessment Date'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='assigned_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assigned Date'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='case_closed_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Case Closed Date'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='due_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Due Date'),
        ),
    ]
