# Generated by Django 6.1 on 2026-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_refund', '0004_alter_auditassessment_assessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundregister',
            name='claim_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Claim Date'),
        ),
        migrations.AlterField(
            model_name='refundregister',
            name='processed_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Processed Date'),
        ),
    ]
