# Generated by Django 6.1 on 2026-08-06 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxpayers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_period', models.CharField(max_length=20, verbose_name='Assessment Period')),
                ('inherent_risk', models.IntegerField(default=0, verbose_name='Inherent Risk (20%)')),
                ('control_risk', models.IntegerField(default=0, verbose_name='Control Risk (15%)')),
                ('detection_risk', models.IntegerField(default=0, verbose_name='Detection Risk (15%)')),
                ('transaction_risk', models.IntegerField(default=0, verbose_name='Transaction Risk (25%)')),
                ('behavior_risk', models.IntegerField(default=0, verbose_name='Behavior Risk (25%)')),
                ('overall_risk_score', models.IntegerField(default=0, verbose_name='Overall Risk Score')),
                ('risk_category', models.CharField(choices=[('critical', 'Critical Risk (80-100)'), ('high', 'High Risk (60-79)'), ('medium', 'Medium Risk (40-59)'), ('low', 'Low Risk (20-39)'), ('minimal', 'Minimal Risk (0-19)')], default='minimal', max_length=20)),
                ('assessment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('under_review', 'Under Review'), ('finalized', 'Finalized')], default='pending', max_length=20)),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('import_sales_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Import/Sales Ratio %')),
                ('consecutive_negative_returns', models.IntegerField(default=0, verbose_name='Consecutive Negative Returns')),
                ('import_zero_sales_periods', models.IntegerField(default=0, verbose_name='Import with Zero Sales Periods')),
                ('high_domestic_purchases', models.BooleanField(default=False, verbose_name='High Domestic Purchases')),
                ('cash_sales_suppression', models.BooleanField(default=False, verbose_name='Cash Sales Suppression')),
                ('sales_variation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sales Variation %')),
                ('recommendations', models.TextField(blank=True)),
                ('audit_priority', models.IntegerField(default=0, verbose_name='Audit Priority (1-10)')),
                ('requires_immediate_audit', models.BooleanField(default=False, verbose_name='Requires Immediate Audit')),
                ('audit_reference', models.CharField(blank=True, max_length=50, verbose_name='Audit Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_registers', to='taxpayers.taxpayermaster')),
            ],
            options={
                'verbose_name': 'Compliance Risk Register',
                'verbose_name_plural': 'Compliance Risk Registers',
                'ordering': ['-overall_risk_score', 'taxpayer'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Critical Alert'), ('warning', 'Warning'), ('information', 'Information')], default='information', max_length=20)),
                ('alert_status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('risk_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='risk_assessment.complianceriskregister')),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='taxpayers.taxpayermaster')),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('import_sales', 'High Import/Low Sales'), ('consecutive_credit', 'Consecutive Credit Filings'), ('import_zero_sales', 'Import with Zero Sales'), ('high_purchases', 'High Domestic Purchases'), ('cash_suppression', 'Cash Sales Suppression'), ('sales_variation', 'Sales Variation'), ('stock_analysis', 'Stock Analysis'), ('filing_compliance', 'Filing Compliance')], max_length=30)),
                ('factor_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('factor_score', models.IntegerField(default=0, verbose_name='Factor Score')),
                ('max_score', models.IntegerField(default=25, verbose_name='Maximum Score')),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical Risk (80-100)'), ('high', 'High Risk (60-79)'), ('medium', 'Medium Risk (40-59)'), ('low', 'Low Risk (20-39)'), ('minimal', 'Minimal Risk (0-19)')], default='minimal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('risk_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='risk_assessment.complianceriskregister')),
            ],
            options={
                'verbose_name': 'Risk Factor Detail',
                'verbose_name_plural': 'Risk Factor Details',
            },
        ),
        migrations.CreateModel(
            name='AuditRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asc_no', models.CharField(max_length=50, unique=True, verbose_name='ASC No.')),
                ('assessment_date', models.DateField(verbose_name='Assessment Date')),
                ('tax_period', models.CharField(max_length=20, verbose_name='Tax Period')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('dzongkhag', models.CharField(max_length=100, verbose_name='Dzongkhag')),
                ('organisation_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, verbose_name='Frequency')),
                ('assessment_type', models.CharField(choices=[('comprehensive', 'Comprehensive Assessment'), ('limited', 'Limited Assessment'), ('desk_audit', 'Desk Audit'), ('investigation', 'Investigation')], max_length=30, verbose_name='Assessment Type')),
                ('declared_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Sales (GST Return)')),
                ('gst_on_declared_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Declared Sales')),
                ('declared_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Import Value (GST Return)')),
                ('gst_on_declared_import', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Declared Import')),
                ('declared_domestic_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Declared Domestic Purchase & Taxable Expenses (GST Return)')),
                ('gst_on_declared_domestic_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Declared Domestic Purchase')),
                ('assessed_sales_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Assessed Sales Turnover')),
                ('actual_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Actual Import Value (eCMS)')),
                ('assessed_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Assessed Import Value')),
                ('gst_on_assessed_import_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Assessed Import Value')),
                ('assessed_domestic_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Assessed Domestic Purchase & Taxable Expenses')),
                ('gst_on_assessed_domestic_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Assessed Domestic Purchase & Taxable Expenses')),
                ('gst_payable_refundable_return', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST Payable / Refundable (GST Return)')),
                ('gst_payable_refundable_assessed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST Payable / Refundable (Assessed)')),
                ('variation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Variation')),
                ('variation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Variation %')),
                ('reason_code', models.CharField(blank=True, max_length=50, verbose_name='Reason Code')),
                ('discrepancy', models.TextField(blank=True, verbose_name='Discrepancy')),
                ('assessment_audit_outcome', models.TextField(blank=True, verbose_name='Assessment/Audit Outcome')),
                ('action_taken', models.TextField(blank=True, verbose_name='Action Taken')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='pending', max_length=20, verbose_name='Status')),
                ('case_closed_date', models.DateField(blank=True, null=True, verbose_name='Case Closed Date')),
                ('assessment_duration_days', models.IntegerField(default=0, verbose_name='Assessment Duration (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Assessor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audit_registers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_audit_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Register',
                'verbose_name_plural': 'Audit Registers',
                'ordering': ['-assessment_date', 'taxpayer_name'],
                'indexes': [models.Index(fields=['asc_no'], name='risk_assess_asc_no_ca7eee_idx'), models.Index(fields=['gstin', 'tax_period'], name='risk_assess_gstin_884494_idx'), models.Index(fields=['assessment_date'], name='risk_assess_assessm_c7ad7e_idx'), models.Index(fields=['status'], name='risk_assess_status_f43f73_idx'), models.Index(fields=['assessment_type'], name='risk_assess_assessm_79101d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['taxpayer', 'assessment_period'], name='risk_assess_taxpaye_f56ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['risk_category'], name='risk_assess_risk_ca_e7da96_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['overall_risk_score'], name='risk_assess_overall_8f445d_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['assessment_status'], name='risk_assess_assessm_c384c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='complianceriskregister',
            unique_together={('taxpayer', 'assessment_period')},
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['taxpayer'], name='risk_assess_taxpaye_39feaf_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['alert_status'], name='risk_assess_alert_s_97cec7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['alert_type'], name='risk_assess_alert_t_9e8cf0_idx'),
        ),
    ]
