# Generated by Django 6.1 on 2026-08-08 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0001_initial'),
        ('taxpayers', '0011_alter_taxpayermaster_dzongkhag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceriskregister',
            name='taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_registers', to='taxpayers.taxpayermaster'),
        ),
        migrations.AlterField(
            model_name='riskalert',
            name='taxpayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='taxpayers.taxpayermaster'),
        ),
    ]
