# Generated by Django 6.1 on 2026-08-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0002_alter_complianceriskregister_taxpayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditregister',
            name='dzongkhag',
            field=models.CharField(choices=[('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, verbose_name='Dzongkhag'),
        ),
    ]
