# Generated by Django 6.1 on 2026-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0003_alter_auditregister_dzongkhag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditregister',
            name='assessment_type',
            field=models.CharField(choices=[('', '---------'), ('comprehensive', 'Comprehensive Assessment'), ('limited', 'Limited Assessment'), ('desk_audit', 'Desk Audit'), ('investigation', 'Investigation')], max_length=30, verbose_name='Assessment Type'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='dzongkhag',
            field=models.CharField(choices=[('', '---------'), ('mongar', 'Mongar'), ('trashigang', 'Trashigang'), ('trashiyangtse', 'Trashiyangtse'), ('lhuntse', 'Lhuntse')], max_length=100, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='frequency',
            field=models.CharField(choices=[('', '---------'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='organisation_type',
            field=models.CharField(choices=[('', '---------'), ('sole_proprietorship', 'Sole Proprietorship'), ('private_company', 'Private Company'), ('public_company', 'Public Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('trust', 'Trust'), ('government', 'Government Entity'), ('other', 'Other')], max_length=30, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='status',
            field=models.CharField(choices=[('', '---------'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
