# Generated by Django 6.1 on 2026-08-08 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0004_alter_auditregister_assessment_type_and_more'),
        ('taxpayers', '0020_rename_taxpayer_master_gstin_idx_taxpayers_m_gstin_1625b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='complianceriskregister',
            name='risk_assess_risk_ca_e7da96_idx',
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='activity',
            field=models.CharField(blank=True, max_length=100, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='assertion_reason',
            field=models.TextField(blank=True, verbose_name='Assertion Reason'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='assigned_assessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_audits', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Assessor'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='audit_focus',
            field=models.TextField(blank=True, verbose_name='Audit Focus'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='audit_selection',
            field=models.CharField(choices=[('selected', 'Selected'), ('review', 'Review'), ('not_selected', 'Not Selected')], default='not_selected', max_length=20, verbose_name='Audit Selection'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='dzongkhag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dzongkhag'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='gst_behaviour_reason',
            field=models.TextField(blank=True, verbose_name='GST Behaviour Reason'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='gst_behaviour_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='GST Behaviour Risk (0-5)'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='organisation_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Organisation Type'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='overall_risk_level',
            field=models.CharField(choices=[('low', 'Low (0.00-1.49)'), ('moderate', 'Moderate (1.50-2.49)'), ('medium', 'Medium (2.50-3.49)'), ('high', 'High (3.50-4.24)'), ('critical', 'Critical (4.25-5.00)')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='overall_risk_reason',
            field=models.TextField(blank=True, verbose_name='Overall Risk Reason'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='primary_assertion',
            field=models.TextField(blank=True, verbose_name='Primary Assertion'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='risk_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Risk ID'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='risk_rank',
            field=models.IntegerField(default=0, verbose_name='Risk Rank'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='secondary_assertion',
            field=models.TextField(blank=True, verbose_name='Secondary Assertion'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='sub_sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sub-Sector'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='taxpayer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Taxpayer Name'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='taxpayer_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Taxpayer Status'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='transaction_risk_reason',
            field=models.TextField(blank=True, verbose_name='Transaction Risk Reason'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='dzongkhag',
            field=models.CharField(choices=[('', '---------'), ('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuntse', 'Lhuntse')], max_length=100, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='frequency',
            field=models.CharField(choices=[('', '---------'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='organisation_type',
            field=models.CharField(choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, verbose_name='Organisation Type'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='assessment_period',
            field=models.CharField(blank=True, max_length=20, verbose_name='Assessment Period'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='control_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Control Risk (0-5)'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='detection_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Detection Risk (0-5)'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='inherent_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Inherent Risk (0-5)'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='overall_risk_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Overall Risk Score (0-5)'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='transaction_risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Transaction Risk (0-5)'),
        ),
        migrations.AlterField(
            model_name='riskfactordetail',
            name='severity',
            field=models.CharField(choices=[('low', 'Low (0.00-1.49)'), ('moderate', 'Moderate (1.50-2.49)'), ('medium', 'Medium (2.50-3.49)'), ('high', 'High (3.50-4.24)'), ('critical', 'Critical (4.25-5.00)')], default='low', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['risk_id'], name='risk_assess_risk_id_fdd0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['overall_risk_level'], name='risk_assess_overall_efebda_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceriskregister',
            index=models.Index(fields=['audit_selection'], name='risk_assess_audit_s_04b871_idx'),
        ),
        migrations.RemoveField(
            model_name='complianceriskregister',
            name='behavior_risk',
        ),
        migrations.RemoveField(
            model_name='complianceriskregister',
            name='risk_category',
        ),
    ]
