# Generated by Django 6.1 on 2026-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0005_remove_complianceriskregister_risk_assess_risk_ca_e7da96_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceriskregister',
            name='risk_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Risk ID'),
        ),
    ]
