# Generated by Django 6.1 on 2026-08-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0006_alter_complianceriskregister_risk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceriskregister',
            name='risk_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Risk ID'),
        ),
    ]
