# Generated by Django 6.1 on 2026-08-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0007_alter_complianceriskregister_risk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceriskregister',
            name='consecutive_credit_filings',
            field=models.IntegerField(default=0, verbose_name='Consecutive Credit Filings'),
        ),
        migrations.AddField(
            model_name='complianceriskregister',
            name='stock_analysis_indicators',
            field=models.IntegerField(default=0, verbose_name='Stock Analysis Indicators'),
        ),
        migrations.AlterField(
            model_name='complianceriskregister',
            name='import_zero_sales_periods',
            field=models.IntegerField(default=0, verbose_name='High Import with Zero Sales Periods'),
        ),
    ]
