# Generated by Django 6.1 on 2026-08-08 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0008_complianceriskregister_consecutive_credit_filings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceriskregister',
            name='audit_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_registers', to='risk_assessment.auditregister', verbose_name='Linked Audit Register'),
        ),
    ]
