# Generated by Django 6.1 on 2026-08-09 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0009_complianceriskregister_audit_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_period', models.CharField(max_length=20, verbose_name='Return Period')),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN')),
                ('taxpayer_name', models.CharField(max_length=200, verbose_name='Taxpayer Name')),
                ('dzongkhag', models.CharField(choices=[('', '---------'), ('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuntse', 'Lhuntse')], max_length=100, verbose_name='Dzongkhag')),
                ('organisation_type', models.CharField(choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, verbose_name='Org Type')),
                ('frequency', models.CharField(choices=[('', '---------'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20, verbose_name='Frequency')),
                ('allotment_date', models.DateField(verbose_name='Allotment Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_allotments', to=settings.AUTH_USER_MODEL, verbose_name='Assessor')),
                ('audit_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotments', to='risk_assessment.auditregister', verbose_name='Audit Register')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allotments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Allotment',
                'verbose_name_plural': 'Audit Allotments',
                'ordering': ['-allotment_date', 'taxpayer_name'],
                'indexes': [models.Index(fields=['return_period'], name='risk_assess_return__510a1a_idx'), models.Index(fields=['gstin'], name='risk_assess_gstin_3dee63_idx'), models.Index(fields=['assessor'], name='risk_assess_assesso_4387cf_idx'), models.Index(fields=['allotment_date'], name='risk_assess_allotme_c33478_idx')],
            },
        ),
    ]
