# Generated by Django 6.1 on 2026-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0010_auditallotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditregister',
            name='gst_on_assessed_domestic_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Assessed Domestic Purchase (Auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='gst_on_assessed_import_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST on Assessed Import Value (Auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='gst_payable_refundable_assessed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST Payable / Refundable (Assessed - Auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='gst_payable_refundable_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='GST Payable / Refundable (GST Return - Auto)'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='variation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Variation (Auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='auditregister',
            name='variation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Variation % (Auto-calculated)'),
        ),
    ]
