# Generated by Django 6.1 on 2026-08-09 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0011_alter_auditregister_gst_on_assessed_domestic_purchase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditallotment',
            name='risk_assess_return__510a1a_idx',
        ),
        migrations.AddField(
            model_name='auditallotment',
            name='tax_period',
            field=models.CharField(default='2026-01-01', max_length=20, verbose_name='Tax Period'),
        ),
        migrations.AlterField(
            model_name='auditallotment',
            name='organisation_type',
            field=models.CharField(choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, verbose_name='Organisation Type'),
        ),
        migrations.AddIndex(
            model_name='auditallotment',
            index=models.Index(fields=['tax_period'], name='risk_assess_tax_per_03ec2e_idx'),
        ),
        migrations.RemoveField(
            model_name='auditallotment',
            name='return_period',
        ),
    ]
