# Generated by Django 6.1 on 2026-08-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0012_remove_auditallotment_risk_assess_return__510a1a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditallotment',
            name='allotment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Allotment Date'),
        ),
    ]
