# Generated by Django 6.1 on 2026-08-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0013_alter_auditallotment_allotment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditallotment',
            name='organisation_type',
            field=models.CharField(choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, verbose_name='Organization Type'),
        ),
    ]
