# Generated by Django 6.1 on 2026-08-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0014_alter_auditallotment_organisation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditallotment',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
