# Generated by Django 6.1 on 2026-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0015_alter_auditallotment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditallotment',
            name='dzongkhag',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Mongar', 'Mongar'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Lhuntse', 'Lhuntse')], max_length=100, null=True, verbose_name='Dzongkhag'),
        ),
        migrations.AlterField(
            model_name='auditallotment',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='auditallotment',
            name='organisation_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Private Company', 'Private Company'), ('Public Company', 'Public Company'), ('Partnership', 'Partnership'), ('State Owned Company', 'State Owned Company'), ('Joint Venture', 'Joint Venture'), ('Foreign Company', 'Foreign Company')], max_length=30, null=True, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='auditallotment',
            name='taxpayer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Taxpayer Name'),
        ),
    ]
