# Generated by Django 6.1 on 2026-08-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0016_alter_auditallotment_dzongkhag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditallotment',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN'),
        ),
    ]
